@startuml

left to right direction
allowmixing

package Parsers {
    component DecisionGraphParser
    component PolicySpaceParser
    component ValueInferenceParser
    class Tree

	DecisionGraphParser --> Tree : "creates"
	PolicySpaceParser --> Tree : "creates"
	ValueInferenceParser --> Tree : "creates"
}

class ColorFunction << (F,#FF7700) Function>>{
	color(Parser.Tree, {number, number}[], boolean) : Map<string, {{number, number}, {number, number}}[]>
}


class colorDecisionGraph extends ColorFunction {	
}

class colorPolicySpace extends ColorFunction {	
}

class colorValueInference extends ColorFunction {	
}

ColorFunction --> Tree : recieves as paramater

@enduml