@startuml

package Client #DDDDDD {

    class Extension

    package Graphviz{}

    package Services{}

    package Localization {
    }
    package Coloring {
    }
   
    Extension -- Graphviz 
    Extension -- Services 
    Extension -- Localization 
    Extension -- Coloring
    Localization -- Services: uses
    Graphviz -- Services :uses
 
}



@enduml