@startuml


class DefaultSection {
    - client: LanguageClient

    - {static} buildLibServiceAppApiInstance():void
    - {static} addGraphvizCommand(context: vscode.ExtensionContext): void
    - {static} addRunCommand({ subscriptions }: vscode.ExtensionContext): void
    - {static} addNewModelCommand({ subscriptions }: vscode.ExtensionContext): void
    - {static} addLocalizationCommand(context: vscode.ExtensionContext)
    - {static} updateStatusBarItem():void
    + {static} deactivate(): Thenable<void> | undefined
    + {static} activateSyntaxColoring(context: vscode.ExtensionContext)
    + {static} activate(context: ExtensionContext):void
}

rectangle extConnection [
    <<External Library>>
    LanguageClient
]


class Client extends extConnection{
    - notifyUser:(msg: string): void
}


class ColoringSection {
}




DefaultSection "1...1" *-- "1...1" Client
DefaultSection -- ColoringSection : uses


@enduml