@startuml

package PolicyModelExtension {
class LocalizationDomain {
    void eventHandlerA()
    void eventHandlerB()
}
}

package LocalizationGUI{

class ReactComponents {}
}

LocalizationGUI ==|> PolicyModelExtension : user events

package WebConsumer {
class LogicDomain {
  void eventHandlerA()
    void eventHandlerB()
}
}

PolicyModelExtension ==|> LocalizationGUI: render




@enduml
