language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "plugin/node_modules"
    - "plugin/client/node_modules"
    - "plugin/server/node_modules"

before_script: 
  - cd plugin
    
script:  
  - npm install
  - npm run compile
  - npm run test

  
after_failure:     
  - for v in /home/travis/.npm/_logs/*.log ; do
    echo $v logtail ======================== ; tail -100 $v ;
    done
  
notifications:
  email:
    recipients:
      - wolfj@post.bgu.ac.il
    on_failure: always