language: node_js
node_js: 
  - "stable"

before_script: 
  - cd plugin
    
script:  
  - npm run clean
  - npm install
  - npm audit fix
  - npm run compile
  - npm run test

  
after_failure:     
  - for v in /home/travis/.npm/_logs/*.log ; do
    echo $v logtail ======================== ; tail -100 $v ;
    done
  
notifications:
  email:
    recipients:
      - wolfj@post.bgu.ac.il
    on_failure: always