language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "plugin/node_modules"
    - "plugin/client/node_modules"
    - "plugin/server/node_modules"

before_script: 
  - cd plugin
    
script:  
  - npm install
  - npm run test

notifications:
  email:
    recipients:
      - wolfj@post.bgu.ac.il
    on_failure: always