@startuml

interface SolverInt {
    +onCompletion(params: TextDocumentPositionParams): CompletionList
    +onCompletionResolve(params: CompletionItem): CompletionItem
    +onDefinition(params: DeclarationParams): LocationLink[]
    +onPrepareRename(params: PrepareRenameParams): Range
    +onRenameRequest(params: RenameParams): WorkspaceEdit
    +onReferences(params: ReferenceParams): Location[]
    +onFoldingRanges(params: FoldingRangeParams): FoldingRange[]
    +onDidOpenTextDocument(opendDocParam: TextDocumentItem): Promise<void>
    +onDidCloseTextDocument(closedDcoumentParams: TextDocumentIdentifier): any
    +onDidChangeTextDocument(params: DidChangeTextDocumentParams): any
    +onDeleteFile(deletedFile: string): any
    +onCreatedNewFile(newFileUri: string): any
    +onOpenFolder(pathUri: string): any
}

class PMSolver implements SolverInt {
    -_documentManagerForFolder: TextDocumentManagerInt
    -_documentManagerSingleFiles: TextDocumentManagerInt
    -_pluginFSPath: string
    -_workspaceFolderFSPath: string
    -_facdeForFolder: LanguageServicesFacade
    -_facdeForFilesFS: { [id: string]: LanguageServicesFacade; }
    -_sovlerReady: boolean
    {field}-_publishDiagnosticsCallback: (uri: string, diagnostics: Diagnostic[], docVersion?: number) => void    
    -isFolderRelevant(fileUri: string): boolean
    -clearDiagnostics(uri: string): void
    -getFSFolderFromUri(uri: string): string
    -getDocManager(uri: string): TextDocumentManagerInt
    -initParser(fileUri: string): Promise<void>
    -facdeCallWrapperForDocumentEvents(params: any, funcName: string, uri: string): Promise<void>
    -facadeCallWrapperForUserEvents(params: any, uri: string, funcName: string): any
    
    +onCompletion(params: TextDocumentPositionParams): CompletionList
    +onCompletionResolve(params: CompletionItem): CompletionItem
    +onDefinition(params: DeclarationParams): LocationLink[]
    +onPrepareRename(params: PrepareRenameParams): Range
    +onRenameRequest(params: RenameParams): WorkspaceEdit
    +onReferences(params: ReferenceParams): Location[]
    +onFoldingRanges(params: FoldingRangeParams): FoldingRange[]
    +onDidOpenTextDocument(opendDocParam: TextDocumentItem): Promise<void>
    +onDidCloseTextDocument(closedDcoumentParams: TextDocumentIdentifier): any
    +onDidChangeTextDocument(params: DidChangeTextDocumentParams): any
    +onDeleteFile(deletedFileUri: string): Promise<void>
    +onCreatedNewFile(newFileUri: string): Promise<void>
    +onOpenFolder(pathUri: string): Promise<void>
    +creatediagnosticsCallback(): (uri: string, errors: SyntaxError[]) => void
}

class Server {
    + connection: Connection
    + fodlerFS: string
    + solver:SolverInt
    + clientSupportsWatchedFiles: boolean
    + hasWorkspaceFolderCapability: boolean
    + runModel(string []): string
}


rectangle extConnection [
    <<External Library>>
    \tConnection
]

class Connection implements extConnection{
    + onInitialize(InitializeParams): InitializeResult
    + onInitialized():void
    + onExit(): void
    + onCompletion:(TextDcoumentPosition): CompletionList
    + onCompletionResolve(CompletionItem): CompletionItem
    + onDefinition(DeclarationParams): LocationLink []
    + onFoldingRange(FoldingRangeParams): FoldingRange []
    + onRefernces(ReferenceParmas): Location []
    + onPrepareRename(PrepareRenameParams): boolean
    + onRenameRequest(RenameParams): WorkspaceEdit
    + onDidChangeWatchedFiles(DidChangeWatchedFilesParams): void
    + onDidChangeTextDocument(DidChangeTextDocumentParams): void
    + onDidCloseTextDocument(DidCloseTextDocumentParams): void
    + onDidOpenTextDocument(DidOpenTextDocumentParams): void
    + onRequestRunModel()
    + onRequestSetPluginDir()
}

interface TextDocumentManagerInt {
}

interface LanguageServicesFacade {
}

Server "1...1" *-- "1...1" Connection
Server "1...1" *-- "1...1" PMSolver

PMSolver o-- "1...*" LanguageServicesFacade
PMSolver *-- "1...1" TextDocumentManagerInt

@enduml