@startuml

'skinparam style strictuml
top to bottom direction
allowmixing

package LanguageUtils #DDDDDD {
    enum PolicyModelsLanguage {
        PolicySpace
        DecisionGraph
        ValueInference
    }
    enum PolicyModelEntityType {
        DGNode
        Slot
        SlotValue
        ValueInference
        InferencePair
        Keyword
    }
    enum PolicyModelEntityCategory {
        FoldRange
        Declaration
        Reference
    }
    class PolicyModelEntity {
        +type: PolicyModelEntityType
        +name: string
        +source?: string
        +syntaxNode: SyntaxNode
        +location: Location
        +category: PolicyModelEntityCategory
        +getType(): PolicyModelEntityType
        +getName(): string
        +getSource(): string
        +setSource(uri: string): void
        +getCategory(): PolicyModelEntityCategory
    }
    
}

@enduml