@startuml

package Server #DDDDDD {

    package LanguageServices {
        class LanguageServicesFacade
        class LanguageServices
        LanguageServices -right-* LanguageServicesFacade
    }

    package Documents{
        interface PMTextDocument
        interface TextDocumentManagerInt 

        TextDocumentManagerInt *-- PMTextDocument
    }

    class SolverInt
    class Connection
    class Server

    Connection -[hidden]- SolverInt

    SolverInt -> LanguageServicesFacade : "uses"
    Server *-- SolverInt
    Server *-- Connection
    

    SolverInt *-- TextDocumentManagerInt
    
}



@enduml