@startuml

package Server #DDDDDD {

    package LanguageServices {
        class LanguageServicesFacade
    }

    package Documents{
        interface PMTextDocument
        interface TextDocumentManagerInt 
    }

    class SolverInt
    class Connection
    class Server

    Connection -[hidden]- SolverInt

    SolverInt -> LanguageServicesFacade : "uses"
    Server *-- SolverInt
    Server *-- Connection
    

    SolverInt *-- TextDocumentManagerInt
    TextDocumentManagerInt *-- PMTextDocument
}



@enduml