@startuml

package Server #DDDDDD {

    package LanguageServices {
        class LanguageServicesFacade
    }

    package Solver {
        class PMSolver
    }

    PMSolver -> LanguageServicesFacade : "uses"
}



@enduml