@startuml

package vscode-languageclient  {
	class LanguageClient
}

package vscode-languageserver  {
	class Connection {

	}
}

package Server #DDDDDD {

	class Server {
	}
}


note "External Library" as n_ext
n_ext .. Connection
n_ext .. LanguageClient
n_ext .. Parsers

package Client #DDDDDD {
    class Client {
    }
}

package Parsers {
    class DecisionGraphParser
    class PolicySpaceParser
    class ValueInferenceParser
}


LanguageClient <-left-> Connection : communicates
Client -up-|> LanguageClient : extends
Server -up-|> Connection : extends



@enduml