@startuml

package vscode-languageclient  {
	class LanguageClient
}

package vscode-languageserver  {
	class Connection {

	}
}

package Server #DDDDDD {

	class Server {
	}
}


note "These are external libraries" as n_ext
n_ext .. Connection
n_ext .. LanguageClient

note "These are external projects that we made for the plugin" as n_ext2
n_ext2 .. Parsers

package Client #DDDDDD {
    class Client {
    }
}

package Parsers {
    class DecisionGraphParser
    class PolicySpaceParser
    class ValueInferenceParser
}


LanguageClient <-left-> Connection : communicates
Client -up-|> LanguageClient : extends
Server -up-|> Connection : extends

Client -down-> Parsers : uses
Server -down-> Parsers : uses


@enduml