
@startuml
left to right direction
skinparam packageStyle rectangle
actor user
actor IDE <<Application>>


rectangle System {

	usecase uc1 as "Create a new policy model"
	usecase uc2 as "Load a project into the IDE"
	usecase writecode as "write Policy Models code"
	usecase uc3_1 as "Graph code colorizing by syntax"
	usecase uc3_2 as "Space code colorizing by syntax"
	usecase uc3_3 as "Value Inference code colorizing by syntax"
	usecase uc3_4 as "Syntax error highlighting"
	usecase uc5 as "Code is auto-completed"
	usecase uc6 as "Running the model locally"
	usecase uc7 as "Localization"
	usecase uc8 as "Jump to definition"
	usecase uc9 as "Smart code Renaming"
	usecase uc10 as "Request folding of scope in code"
	usecase uc11 as "Graphviz visualization"
	usecase uc11_1 as "Decision graph visualization"
	usecase uc11_2 as "Policyspace visualization"


	user--> uc1	
	user--> uc2
	user--> writecode 
	uc3_1 --> IDE
	uc3_2 --> IDE
	uc3_3 --> IDE
	uc3_4 --> IDE
	
	writecode .down.> uc3_4 : <<extends>>
	writecode .down.> uc3_1 : <<extends>>
	writecode .down.>  uc3_2 : <<extends>>
	writecode .down.>  uc3_3 : <<extends>>
	writecode .right.> uc5 : <<extends>>
	
	uc5 --> IDE
	user--> uc6
	user--> uc7
	user--> uc8
	uc8 --> IDE
	user--> uc9 
	uc9  --> IDE
	user--> uc10
	uc10 --> IDE
	uc2--> IDE
	uc7 --> IDE
	user --> uc11
	uc11 ..> uc11_1: <<extneds>>
	uc11 ..> uc11_2: <<extneds>>

	uc11_1 --> IDE
	uc11_2 --> IDE
}

@enduml

